name: Project check

on:
  push:
    branches:
      - master
  pull_request:
    branches: '*'

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3

    - uses: actions/checkout@master
      name: Checkout

    - name: Install dependencies
      run: pnpm i

    - name: Run checks
      run: pnpm lint
